ADD more complete json output
markri/wp-sec pull request #3
Opened 2016-11-16 15:24 UTC by emaV

This patch allow the `wp-sec` command to return a json object with the list of vulnerabilities and not only a count.

2016-11-16 15:33 UTC, markri requested changes
Thnx for your changes. Maybe you can make something like:

```
core:
   count: 1
   details: { }
```

Data is somehow redundant this way because count can be calculated by counting the details. But since the JSON won't be megabytes long (which would mean serious trouble :-)) it is not a problem. And we give some kind of BC

And also the connected BDD test

2016-11-16 20:23 UTC, emaV commented
Uhm, for some reason behat doesn't like the new JSON with `count` and `details`...

2016-11-16 20:42 UTC, markri commented
Thnx for updating. I just checked the behat test. It's the blank space at the end of the json edited in the feature. Once removed it should pass :-)

2016-11-16 21:12 UTC, markri approved these changes

2016-11-16 21:12 UTC, merged

2016-11-17 09:28 UTC, emaV commented
Thank you!